### ISSUE TITLE
Federal Districts (Федеральные округа)?

### ISSUE THREAD

**Issue by eduard93** [timurkanaz/Russia_geojson_OSM#1]
Can you please add a map of the Federal Districts (Федеральные округа)?

Or just share the python scripts for `Russia_regions.geojson`? i will try to modify it to get the map of the Federal Districts.

Thank you.

**Comment by timurkanaz** [comment]
@eduard93  Hi, I have added geometry for each Federal District. You can check here: [Federal Districts](https://github.com/timurkanaz/Russia_geojson_OSM/tree/master/GeoJson's/Federal%20Districts)

**Comment by eduard93** [comment]
Thank you!

**Comment by eduard93** [comment]
Is that just Mapbox issues?
![image](https://user-images.githubusercontent.com/5127457/143422073-574a0b4d-ee00-4f60-8438-6fded0c434c6.png)

**Comment by timurkanaz** [comment]
@eduard93 No, It's issue of projection,unfortunately

**Comment by eduard93** [comment]
Fair enough.
