### ISSUE TITLE
Отсутствует Московская область

### ISSUE THREAD

**Issue by zubosem** [timurkanaz/Russia_geojson_OSM#2]
Привет, Тимур.
У тебя потерялась Московская область в регионах GeoJson's/Regions/
г. Москва есть в городах, контур области можно найти в Countries/Russia_regions.geojson.
Но самой Московской области с разбивкой по районам нет.
Сможешь её найти и в репозиторий воткнуть?
Спасибо.

**Comment by timurkanaz** [comment]
> Привет, Тимур.
> У тебя потерялась Московская область в регионах GeoJson's/Regions/
> г. Москва есть в городах, контур области можно найти в Countries/Russia_regions.geojson.
> Но самой Московской области с разбивкой по районам нет.
> Сможешь её найти и в репозиторий воткнуть?
> Спасибо.

Привет, МО будет добавлена вечером/ночью.

**Comment by zubosem** [comment]
Круто, спасибо. Еще, пользуясь случаем, спрошу. Если ты делал полигоны на основе какого-то источника, там нет информации о кадастровых регионах и районах для этих полигонов? Например, Татарстан - 16 кадастровый **регион**, Казань - 16:50 кадастровый **район** в регионе 16. Еще есть деление на кадастровые **кварталы**. По идее кадастровое деление делается на основе территориальной принадлежности. Скорее всего кадастровым кварталам у тебя соответствуют полигоны в Казани (это третья секция номера в кадастровом номере недвижимости). Потому что сам город Казань не является кадастровым регионом, как Питер или Москва, к примеру (https://e-ecolog.ru/e-cad/16:50). Это было бы супер полезно, конечно.
Спасибо.

**Comment by timurkanaz** [comment]
@zubosem , нет, я парсил окато/ откмо, брал оттуда названия мунициипальных/городских округов и шел в API OpenStreetMap. Там я делал обычный GET запрос и получал обратно координаты, которые преобразовывал в геометрии.  Именно кадастровыми справочниками не пользовался.

**Comment by timurkanaz** [comment]
[Московская область Moscow Region](https://github.com/timurkanaz/Russia_geojson_OSM/blob/master/GeoJson's/Regions/CFO/%D0%9C%D0%BE%D1%81%D0%BA%D0%BE%D0%B2%D1%81%D0%BA%D0%B0%D1%8F%20%D0%BE%D0%B1%D0%BB%D0%B0%D1%81%D1%82%D1%8C_Moscow%20Region.geojson)
